// Copyright (c) 2026 Carsten Hess
// SPDX-License-Identifier: MIT
// See LICENSE in the repository root.

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    // Pure unit tests: settings types, DiffView, and the agent event reducers
    // (useAgentStore.test.ts is a table-driven vitest suite covering every
    // SerializableAgentEvent kind; the *.preview.test.ts suite covers the
    // approval-preview path; ipc-contract.test.ts is the TS-side IPC contract
    // drift detector — feeds the golden JSON fixtures through the reducer +
    // asserts DTO field shapes).
    include: [
      "src/components/settings/**/*.test.ts",
      "src/components/chat/Conversation.test.ts",
      "src/components/chat/Conversation.layout.test.ts",
      "src/components/chat/Conversation.window.test.tsx",
      "src/components/chat/DiffView.test.ts",
      "src/components/chat/InflightBar.test.ts",
      "src/components/chat/InlineMarkdown.test.ts",
      "src/components/chat/MarkdownLink.test.tsx",
      "src/components/chat/messageArgLabel.test.ts",
      "src/components/common/BootSplash.test.tsx",
      "src/components/common/JsonView.test.ts",
      "src/components/common/MnemoLogo.test.tsx",
      "src/components/common/SourceEditor.test.ts",
      "src/components/common/SplashCard.test.tsx",
      "src/components/projects/InstanceConflictDialog.test.tsx",
      "src/components/settings/sections/ModelCombobox.test.tsx",
      "src/components/layout/InputBar.test.ts",
      "src/components/layout/InputBar.steerEdit.test.ts",
      "src/components/views/BacklogView.test.ts",
      "src/components/views/BacklogView.test.tsx",
      "src/components/views/DiffViewer.test.ts",
      "src/components/views/GitView.test.ts",
      "src/components/views/GraphView.test.ts",
      "src/components/views/gitLanes.test.ts",
      "src/components/views/LlmTraceView.test.ts",
      "src/components/views/LlmTraceView.versionSkip.test.ts",
      "src/components/views/MemoryDebugView.test.ts",
      "src/components/views/PlanProgress.expand.test.ts",
      "src/components/views/PlanStepRow.test.tsx",
      "src/components/views/TraceStats.tooltip.test.ts",
      "src/hooks/useAgentStore.test.ts",
      "src/hooks/useAgentStore.preview.test.ts",
      "src/hooks/useAgentEvents.dispatch.test.ts",
      "src/hooks/useAgentEvents.registration.test.ts",
      "src/hooks/browserReveal.test.ts",
      "src/hooks/deltaFlush.test.ts",
      "src/hooks/agentEventReducer.memory.test.ts",
      "src/hooks/agentState.images.test.ts",
      "src/hooks/agentState.test.ts",
      "src/hooks/useBrowserRect.test.ts",
      "src/hooks/rightPanelViews.test.ts",
      "src/lib/ipc-contract.test.ts",
      "src/lib/answerSelect.test.ts",
      "src/lib/attachImages.test.ts",
      "src/lib/contextMenu.test.ts",
      "src/lib/delegationNotes.test.ts",
      "src/lib/endpoints.test.ts",
      "src/lib/format.test.ts",
      "src/lib/inflightPanelPref.test.ts",
      "src/lib/language.test.ts",
      "src/lib/mdEdit.test.ts",
      "src/lib/messageEquality.test.ts",
      "src/lib/openFile.test.ts",
      "src/lib/openChatLink.test.ts",
      "src/lib/markdownRendering.test.ts",
      "src/lib/planSteps.test.ts",
      "src/lib/promptHistory.test.ts",
      "src/lib/protectedPathWarning.test.ts",
      "src/lib/slash.test.ts",
      "src/lib/sounds.test.ts",
      "src/lib/textareaAutosize.test.ts",
      "src/styles/scrollbar.test.ts",
      "src/styles/themeContrast.test.ts",
      "src/hooks/appearance.test.ts",
      "src/lib/toolCardPaths.test.ts",
      "src/lib/traceStats.test.ts",
      "src/components/chat/ToolImage.test.ts",
      "src/components/layout/MainPanel.tabStyle.test.ts",
      "src/components/layout/ExecutingStepPopup.test.tsx",
      "src/components/layout/StatusBar.truncate.test.ts",
      "src/components/layout/RightPanel.width.test.tsx",
      "src/components/projects/indexingOverlay.test.ts",
      "src/components/projects/projectPickerPhases.test.ts",
      "src/components/resizeHandleMotif.test.ts",
      "src/lib/tauri.test.ts",
      "src/lib/windowRestore.test.ts",
      "src/lib/vitestInclude.test.ts",
      "src/App.shellRender.test.ts",
    ],
  },
});
